### ISSUE TITLE
linkify takes forever with parse_email=True

### ISSUE THREAD

**Issue by gaearon** [jsocol/bleach#124]
I presume it's a bug:

    >>> bleach.linkify("<br>test@test.com", parse_email=True)

takes forever to execute on 1.4.

**Comment by vivazzi** [comment]
I have this infinite loop too. Bleach version - 1.4.1.
my example:
```>>> bleach.linkify('<p>test<br/>, email test@mail.ru</p>')```

In debug I have seen next result like this:
```u'" ><a href="<a href="mailto:test@mail.ru" >mailto:test@mail.ru</a>" >test@mail.ru</a>'```
It likes this recursion.

Alhought, next test is passed:
```
>>> bleach.linkify('<p>test email test@mail.ru</p>')
u'<p>test email <a href="mailto:test@mail.ru">test@mail.ru</a></p>'
```
