### ISSUE TITLE
Leading parenthesis removed when linkifying and skipping links. 

### ISSUE THREAD

**Issue by ialbert** [jsocol/bleach#146]
When using callbacks to override linkifying the leading parenthesis around a "skipped" link will not be  present in the output. 

Example input:

    foo.com
    (foo.com)
    [foo.com]

Example output (note the missing `(` in the second line)

    foo.com
    foo.com)
    [foo.com]
    
Code:

    import bleach

    def full_links(attrs, new):
        # Don't linkify non http links
        text = attrs['_text']
        if text[:4] not in ('http', 'ftp:'):
            return None
        return attrs

    callbacks = [
        full_links,
    ]

    text = """
    foo.com
    (foo.com)
    [foo.com]
    """
    html = bleach.linkify(text, callbacks=callbacks)
    print html

**Comment by jsocol** [comment]
So a minimal test case is something like:

```python
intext = '(test.py)'
expect = '(test.py)'
assert bleach.linkify(intext, callbacks=[lambda *a: None]) == expect
```

(Please correct me if I'm wrong, just marking it for myself.)

**Comment by ialbert** [comment]
yes indeed! thanks.

**Comment by jsocol** [comment]
[Found the problem](https://github.com/jsocol/bleach/blob/master/bleach/__init__.py#L349-L350) while looking at another issue, so I haven't fixed it yet.

**Comment by ialbert** [comment]
Thanks for the fix.
