### ISSUE TITLE
Stripps image tag, when src attribute is like <img alt="" src="data:;base64,sdfdsffdfsdf..." />

### ISSUE THREAD

**Issue by arthur-s** [jsocol/bleach#148]
not working for base64 images, it stripps tag, even when i use custom filter:
def filter_src_for_image(name, value):
    return True

ATTR = {
        'a': ['href', 'title'],
        # 'img': ['src', 'alt', 'title', 'style'],
        'img': filter_src_for_image,
    }

**Comment by arthur-s** [comment]
already done. i decided to clean in another way, with html5lib

**Comment by ztane** [comment]
@arthur-s  do note that allowing data uris means that you can embed a html document in the `<a href>` and thus are open to possible XSS.

**Comment by arthur-s** [comment]
@ztane Thanks. You mean like this?
```
<img width="16" height="16" alt="star" src="data:image/gif;base64,R0lGODlhEAAQAMQ...AAAA"/><script>alert('haha')</script><img src="data:image/gif;base64,AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" />
```
i inserted script tag to data uri. Thanks for saying)
