### ISSUE TITLE
Can't allow style background-image with value url('foo')

### ISSUE THREAD

**Issue by bsturmfels** [jsocol/bleach#152]
Bleach strips out the "background-image" style when the value contains parentheses, even when "background-image" is an allowed style.

```
>>> import bleach
>>> bleach.clean(
...    """<div style="background-image: url('foo');"></div>""",
...    tags=['div'], attributes=['style'], styles=['background-image'])

'<div style=""></div>'
```

I would expect this to return:

```
'<div style="background-image: url('foo');"></div>'
```

I've tested this against Bleach 4e425f767b and html5lib 0.999.

**Comment by bsturmfels** [comment]
After a little more searching, I found this comment indicating that the current behaviour is intentional:
https://github.com/jsocol/bleach/issues/91#issuecomment-14857108

**Comment by jsocol** [comment]
Yeah, this is beyond the design intentions of bleach. There has to be a cut-off at which point the added complexity is not worth supporting a risky and small use case. I honestly think Bleach has gone past the sane spot where it should stop and ask: "Are you _sure_ this is the right thing to do?" On #91, I never followed up, but should have pointed out that it absolutely does support `poster` attributes.

This is a huge problem of trust. Either you trust your users to write HTML, or you don't.

Bleach tries to occupy a really uncomfortable spot in the middle. The original use case was essentially "allow BBCode that looks like HTML", and if you look at the default whitelists, that's still reflected there. But people constantly seem to want to somehow be "safe" while also allowing untrusted users to screw up the entire layout, which I don't really understand.

There's probably space for an HTML5-parsing-algorithm, blacklist-based sanitizer—or it's easy enough to build with html5lib's sanitizer. I don't want to build or use that project, but it seems like a lot of people want footguns, so it'd probably be reasonably popular.

Sorry, I don't mean to go off on you. I'm just really not interested in this library moving in this direction. It's gone too far as is. But it's open source. If you disagree and want to fork it, there'll probably be a bunch of users that follow.

**Comment by bsturmfels** [comment]
Thanks for the really useful library by the way! :)

**Comment by jsocol** [comment]
:) glad you find it helpful!
