### ISSUE TITLE
Some tests fail

### ISSUE THREAD

**Issue by frispete** [jsocol/bleach#156]
Hello,

you might be interested in the fact, that some tests fail:
```
[    7s] ...............................................F..........F.............................................F.......................
[    7s] ======================================================================
[    7s] FAIL: bleach.tests.test_links.test_email_link('email to <a href="james@example.com" rel="nofollow">james@example.com</a>', True, 'email to <a href="james@example.com">james@example.com</a>')
[    7s] ----------------------------------------------------------------------
[    7s] Traceback (most recent call last):
[    7s]   File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
[    7s]     self.test(*self.arg)
[    7s]   File "/home/abuild/rpmbuild/BUILD/bleach-1.4.1/bleach/tests/test_links.py", line 87, in _check
[    7s]     eq_(o, linkify(i, parse_email=p))
[    7s] AssertionError: 'email to <a href="james@example.com" rel="nofollow">james@example.com</a>' != u'email to <a>james@example.com</a>'
[    7s] 
[    7s] ======================================================================
[    7s] FAIL: Only create links if there's a protocol.
[    7s] ----------------------------------------------------------------------
[    7s] Traceback (most recent call last):
[    7s]   File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
[    7s]     self.test(*self.arg)
[    7s]   File "/home/abuild/rpmbuild/BUILD/bleach-1.4.1/bleach/tests/test_links.py", line 170, in test_only_proto_links
[    7s]     eq_(out_text, linkify(in_text, [only_proto]))
[    7s] AssertionError: 'a ex.mp <a href="http://ex.mp">http://ex.mp</a> <a href="/foo">bar</a>' != u'a ex.mp <a href="http://ex.mp">http://ex.mp</a> <a>bar</a>'
[    7s] 
[    7s] ======================================================================
[    7s] FAIL: bleach.tests.test_links.test_elements_inside_links
[    7s] ----------------------------------------------------------------------
[    7s] Traceback (most recent call last):
[    7s]   File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
[    7s]     self.test(*self.arg)
[    7s]   File "/home/abuild/rpmbuild/BUILD/bleach-1.4.1/bleach/tests/test_links.py", line 441, in test_elements_inside_links
[    7s]     linkify('<a href="#">hello<br></a>'))
[    7s] AssertionError: '<a href="#" rel="nofollow">hello<br></a>' != u'<a>hello<br></a>'
[    7s] 
[    7s] ----------------------------------------------------------------------
[    7s] Ran 128 tests in 0.405s
```
I'm building your package on openSUSE build service, where it is built against a variete of distributions:

https://build.opensuse.org/package/show/home:frispete:python/python-bleach

I will leave this build failing for a few days, before I disable the tests (or update the package)

**Comment by frispete** [comment]
Okay, disabled tests for now for your package.

Please send me a note, when you fixed them.

FYI: distributions, that build with tests enabled will help you greatly to avoid bitrot.

**Comment by jsocol** [comment]
That's bizarre, because it looks like these only differ by type, and in python2.7, unicode objects that only contain ascii should compare as equal to the same bytes in bytestrings, i.e.. `assert u'a' == b'a'` should pass.

Are there any other projects that have seen this kind of failure?

**Comment by jsocol** [comment]
@frispete oh, sorry, I edited your original report to show the output in plaintext, and now I see the issues.

Can you tell me a little more about the combinations of distro/python versions which failed? Because everything's been [green on travis](https://travis-ci.org/jsocol/bleach) for a while.

**Comment by frispete** [comment]
Dear James, I'm glad to inform you, that this issue vanished. I enabled the tests again, and expected them to fail like a month before, but now they succeed. Hmm. Strange. 

I build a bunch of packages against a number of openSUSE distributions (the current updated state, not the released one). That nicely reflects, how those packages land in the wild, while build service provides an always consistent, reproducible build (usually).
