### ISSUE TITLE
Weird behavior with self closing tags

### ISSUE THREAD

**Issue by dbi** [jsocol/bleach#164]
This looks like unintended behavior.

```python
import bleach
bleach.clean('<u/>hello', tags=['u'])
# => u'<u>hello</u>'
```

It works with `<br/>` tags tho.

```python
bleach.clean('<br/>hello', tags=['br'])
# => u'<br>hello'
```

But we use bleach to clean html from an unknown user and we have no control over the kind of html they write so I feel it should handle self closed `<u/>` tags as well. Now we get full pages of underlined text.

```python
bleach.clean('<u/>hello\nsecond row', tags=['u'])
# => u'<u>hello\nsecond row</u>'
```

**Comment by jsocol** [comment]
`u` is a [phrasing element](http://www.w3.org/TR/html-markup/u.html#u), not a [void element](http://www.w3.org/TR/html-markup/syntax.html#void-element). Here are some relevant phrases from that link:

- "start tags consist of the following parts, in exactly the following order: [...] Optionally, a "/" character, which may be present only if the element is a void element."
- "Void elements only have a start tag; end tags must not be specified for void elements."
- "A non-void element must have an end tag, unless the subsection for that element in the HTML elements section of this reference indicates that its end tag can be omitted."

Some tags, like [`li`](http://www.w3.org/TR/html-markup/li.html#li-tags) permit omitting the end tag in certain circumstances, `u` is not one of them.

This behavior is correct, according to the HTML5 parsing algorithm.

**Comment by dbi** [comment]
Thanks for the explanation! We will be searching for and expanding tags like that (except void elements) before sending it to bleach to solve our problem and deal with xhtml and malformed html from email clients.
