### ISSUE TITLE
Bleach Strips Allowed Tags

### ISSUE THREAD

**Issue by mmulqueen** [jsocol/bleach#166]
I've asked Bleach to allow html, head and body tags (I'm using bleach to santise HTML emails and then presenting them in an iframe, so its desirable to retain these tags. However it seems to strip them anyway. This messes up styling. Is this intentional and how can I change this behaviour?

**Comment by jsocol** [comment]
[Bleach is not designed to operate on full documents](http://bleach.readthedocs.org/en/latest/goals.html#non-goals). Bleach is for document fragments. Bleach would be appropriate for sanitizing untrusted user content that ends up somewhere in the body of the document you're including in the iframe, but not for sanitizing the whole document.
